### ISSUE TITLE
Enhancement: Add Automated Tests for Core Logic & UI

### ISSUE THREAD

**Issue by rob2rhyme** [rob2rhyme/SafeSweep-mac#6]
## Add Automated Tests for Core Logic & UI

**Problem:**  
Right now, CommandRunner and ReportBuilder have no automated tests. We also lack a simple UI test to catch regressions. Adding tests ensures long-term robustness.

**Proposed Solution:**  
1. **Unit Tests**  
   - Under `test/`, create `command_runner_test.dart`:
     - Mock `Process.start` using `package:mockito` or `process_run`’s test utilities.  
     - Verify that `runCommand("echo", ["test"])` returns expected `stdOutput`.  
   - Create `report_builder_test.dart`:
     - Feed a fake list of `CommandResult` (some with exitCode=0, some exitCode=1) and confirm `buildTextReport` correctly formats sections and error messages.

2. **Widget Test (Golden)**  
   - Under `test_widget/`, create `home_screen_test.dart`:
     - Render `HomeScreen` in a test environment.  
     - Verify that initial UI shows “Run All Checks” button and an empty report area.  
     - (Optional) Write a golden file test that captures screenshot of HomeScreen in light mode.

3. **CI Integration**  
   - Add a simple GitHub Actions workflow (`.github/workflows/ci.yml`) that runs:  
     ```yaml
     name: CI

     on: [push, pull_request]

     jobs:
       build_and_test:
         runs-on: macos-latest
         steps:
           - uses: actions/checkout@v3
           - name: Set up Flutter
             uses: subosito/flutter-action@v2
             with:
               flutter-version: '3.0.0'
           - name: Install dependencies
             run: flutter pub get
           - name: Run unit tests
             run: flutter test
         env:
           CI: true
     ```
   - This ensures every PR triggers tests on a macOS runner.

**Acceptance Criteria:**  
- `flutter test` passes with 100% of the new tests.  
- CI workflow triggers and reports test success/failure.  
- Tests cover both success and failure paths in `CommandRunner` and look for correctly formatted report output.
